name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: |
          rm -rf out
          npm run build
          cp -r out/* .
          touch .nojekyll
          echo "Listing root contents:"
          ls -la
          
      - name: Debug Info
        run: |
          echo "Checking for index.html:"
          find . -maxdepth 1 -name "index.html"
          echo "Checking directory structure:"
          tree . || ls -R .
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true
          clean-exclude: |
            .nojekyll
